# Generated by Django 4.0.5 on 2022-09-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_language_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
