# Generated by Django 4.0.5 on 2022-09-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_usercourse_mycourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MyCourse',
        ),
    ]
