# Generated by Django 4.0.5 on 2022-09-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_author_skill_delete_mycourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='yt_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
