# Generated by Django 4.0.5 on 2022-09-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_author_yt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='skill',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='yt_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
